version: '3'
services:
  postgres:
    #version postgres 9.6.9
    image: postgres
    container_name: "postgres"
    restart: always
    volumes:
      - ./app:/dados/postgree/
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_MULTIPLE_DATABASES: postgres
    ports:
      - 54320:5432

  #micro_cliente:
  #  build: micro_cliente
  #  hostname: micro_cliente
  #  container_name: "micro_cliente"
  #  restart: always
  #  ports:
  #    - 8081:8081
  #  links:
  #    - postgres